sudo: required
dist: trusty

language: cpp

addons:
  apt:
    packages:
      - build-essential
      - cmake
      - g++
      - gcc
      - git
      - libudev-dev
      - libevdev-dev
      - libyaml-cpp-dev

script:
  - ./build
