#!/usr/bin/env bash

set -e # exit on failures

base_repo='https://gitlab.com/interception/linux'
projects=('tools' 'plugins/space2meta' 'plugins/caps2esc' 'plugins/hideaway')
package_dir='package'
install_dir="${package_dir}/usr/local/bin"

git_checkout() {
  local project=$1
  local repo="${base_repo}/${project}"
  git clone  --depth 1 -b master --single-branch "$repo" "$project"
}

build_project() {
  local project=$1
  local build_dir="${project}/build"

  git_checkout "$project"
  mkdir "$build_dir"
  cd "$build_dir"
  cmake ..
  make
  mkdir "$install_dir"
  make install DESTDIR="$install_dir"
}

for project in "${projects[@]}"; do
  build_project "$project"
done

tree
